title: Vidamina
author: Josito
email: josito@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Te ayudamos a llevar una vida saludable con consejos, complementos vitáminicos y alimentación natural.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Vidamina
  tagline: vitaminas y alimentación natural
  date_format: "%b %-d, %Y"
  #date_format: "%e /%m/%Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: vidamina
    #github:  vidamina
    #rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#- about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed